[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "Svetlana"
authors = [{name = "Imactiv-3D, CNRS, Université de Toulouse", email = "clement.cazorla31@gmail.com"}]
dynamic = ["version", "description"]
